DROP TABLE IF EXISTS AIRPORTS;
 
CREATE TABLE AIRPORTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  AIRPORT_CODE VARCHAR(250) NOT NULL,
  AIRPORT_DESCRIPTION VARCHAR(250) NOT NULL,
  AIRPORT_X_CORDINATE INT DEFAULT 0,
  AIRPORT_Y_CORDINATE INT DEFAULT 0
);

COMMIT;